<?php

namespace Nano\EpresseBundle\Repository;

/**
 * ParutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParutionRepository extends \Doctrine\ORM\EntityRepository
{
}
