<?php

namespace Nano\EpresseBundle\Repository;

/**
 * PeripheriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeripheriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
