utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

epresse:
    resource: "@EpresseBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: '@AppBundle/Controller/'
    type: annotation
